### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by babeuloula**

### CODE REVIEW

**Comment by zit-hb** [comment]
Great, thanks a lot for the translation! Could you also include a translation of the tooltips? They are shown on the starting page. You can find them in `src/Swd/AnalyzerBundle/Resources/tooltips`.

Since they are full sentences they can likely be well translated using DeepL. My French is not very good though, so I am not able to spot any potential mistakes. This is the automated translation:

```
Si vous voulez référencer les résultats, vous devez les trier en ordre croissant par l'id de la demande ou du paramètre. De cette façon, les nouveaux résultats sont ajoutés en bas de la liste et il y a toujours les mêmes éléments sur une page.
Si vous cliquez sur l'icône en forme d'engrenage, vous pouvez définir et supprimer des filtres pour n'afficher que ce que vous voulez vraiment voir.
Vous pouvez cliquer directement sur la plupart des entrées du tableau pour ajouter un nouveau filtre. Cela permet de gagner beaucoup de temps ! Les anciens et les nouveaux filtres sont fusionnés et les filtres vides sont supprimés de l'url.
Vous pouvez utiliser des astérisques comme caractères de remplacement pour la plupart des filtres textuels.
Shadow Daemon est très flexible et fonctionne pour la plupart des applications web. Dans de nombreux cas, aucune modification du code source n'est nécessaire, le plugin du connecteur peut être directement chargé lors de l'exécution d'un script.
Vous pouvez modifier les valeurs par défaut comme le nombre d'entrées par page ou l'ordre de tri dans les paramètres. Les autres utilisateurs ne sont pas affectés.
Les filtres des listes noires sont très sensibles et ont un taux élevé de faux positifs. C'est la raison pour laquelle les impacts de tous les filtres correspondants sont additionnés. Ce n'est que si la somme est supérieure à un seuil qu'elle est classée comme une attaque. Ce seuil peut varier d'un profil à l'autre.
Les règles et les filtres ne sont vérifiés que lorsqu'une demande arrive. Ainsi, si vous ajoutez ou modifiez une règle après que la demande a été enregistrée dans la base de données, elle ne sera pas considérée comme une menace.
```

**Comment by zit-hb** [comment]
Also, I am currently working on a migration to Symfony 4. Unfortunately it turned out to be more work than expected. I am planning a new release of the web interface once the migration is done.

**Comment by babeuloula** [comment]
@zit-hb Hello, I've just add the translation for tooltips. With deepL you do a great job.

What do you understand with `The translation seems to use the formal form of address.` ?

**Comment by zit-hb** [comment]
> @zit-hb Hello, I've just add the translation for tooltips. With deepL you do a great job.

Thanks!

> What do you understand with `The translation seems to use the formal form of address.` ?

So it is using `vous` instead of `tu`. In German we have the same thing: `sie` and `du`. Using the polite form `sie` would look a bit strange for tooltips in my opinion, but I am not sure how the French feel about `vous` in regards to this.

**Comment by babeuloula** [comment]
OK I understand, `tu` is more familar, `vous` is more polite because you don't know the user.

**Comment by zit-hb** [comment]
And merged! Are you interested in getting added to [the credits](https://shadowd.zecure.org/about/credits/)? If yes, please let me know what name I should use and if there should be a link to your Github/Twitter/whatever account.

**Comment by babeuloula** [comment]
You can credit with BaBeuloula and my github account. 
Thanks

**Comment by zit-hb** [comment]
It was just released in version 2.0.5 :tada:

**Pull request merged**
